version: 2

jobs:
  macos:
    macos:
      xcode: "10.2"
    steps:
      - checkout
      - run:
          name: Install libressl
          command: brew install libressl
      - run:
          name: Compile code
          command: swift build
      - run:
          name: Run unit tests
          command: swift test
      - run:
          name: Compile code with optimizations
          command: swift build -c release

  linux:
    docker:
      - image: codevapor/swift:4.1
    steps:
      - checkout
      - run:
          name: Compile code
          command: swift build
      - run:
          name: Run unit tests
          command: swift test
      - run:
          name: Compile code with optimizations
          command: swift build -c release

  linux-vapor:
    docker:
      - image: vapor/swift:5.1-bionic
    steps:
      - checkout
      - run: apt-get update; apt-get install -y libssl-dev zlib1g-dev
      - run:
          name: Clone Vapor
          command: git clone -b master https://github.com/vapor/vapor.git
          working_directory: ~/
      - run:
          name: Switch Vapor to this WebSocket revision
          command: |
            swift package edit WebSocket --path ~/../
          working_directory: ~/vapor
      - run:
          name: Run Vapor unit tests
          command: swift test
          working_directory: ~/vapor
workflows:
  version: 2
  tests:
    jobs:
      - linux
      - macos
      - linux-vapor

  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - linux
      - macos
